[build]
builder = "NIXPACKS"

[nixpacks]
plan = '''
[environment]
GOMODCACHE = "/go/cache"

[phases.setup]
nixPkgs = ["go"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -o blooddnr ./main.go"]

[start]
cmd = "./blooddnr"
'''